version: '3'

services:
  blog:
    platform: linux/amd64
    image: blog
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: hugo-blog
    volumes:
      - ..:/src
    working_dir: /src
    ports:
      - 1313:1313
    stdin_open: true
    tty: true